export const advertisements_mock = [{
  "id": "1",
  "name": "Стул старинный",
  "description": "Очень красивый",
  "price": 2000,
  "createdAt": "2022-08-12T20:16:55.351Z",
  "views": 20,
  "likes": 2,
  "imageUrl": "",
},
{
  "id": "2",
  "name": "Ведро снега",
  "description": "Последняя возможность купить по выгодной цене!",
  "price": 3000,
  "createdAt": "2024-09-11T15:00:11.859Z",
  "views": 0,
  "likes": 0,
  "imageUrl": "https://artlogic-res.cloudinary.com/w_1600,h_1600,c_limit,f_auto,fl_lossy,q_auto/artlogicstorage/gridchinhall/images/view/861e5cb8124dcdf2cd7914bae4b6e276j/gridchinhallgallery-katya-rozhkova-a-bucket-of-snow-1-1-2019.jpg",
},
{
  "id": "3",
  "name": "Плащ невидимка",
  "price": 10000100,
  "createdAt": "2024-08-12T20:16:55.351Z",
  "views": 900,
  "likes": 19,
  "imageUrl": "",
  "description": "",
},
{
  "id": "4",
  "name": "Ковер",
  "description": "Стильный модный, как у бабушки в деревне :)))",
  "price": 5000,
  "createdAt": "2024-07-12T20:16:55.351Z",
  "views": 2000000,
  "likes": 2,
  "imageUrl": "",
},
{
  "id": "5",
  "name": "Носки",
  "price": 6000,
  "createdAt": "2024-06-12T20:16:55.351Z",
  "views": 0,
  "likes": 0,
  "imageUrl": "",
},
{
  "id": "6",
  "name": "Картонная коробка",
  "description": "Прочная.",
  "price": 7000,
  "createdAt": "2024-04-12T20:16:55.351Z",
  "views": 1,
  "likes": 0,
  "imageUrl": "",
},
{
  "id": "7",
  "name": "Угловой диван",
  "description": "Стих для привлечения внимания: дама сдавала в багаж диван, чемодан, саквояж, картину, корзину, картонку и маленькую собачонку. выдали даме на станции четыре зеленых квитанции о том, что получен багаж: диван, чемодан, саквояж, картина, корзина, картонка и маленькая собачонка. вещи везут на перрон. кидают в открытый вагон. готово. уложен багаж: диван, чемодан, саквояж, картина, корзина, картонка и маленькая собачонка. но только раздался звонок, удрал из вагона щенок. хватились на станции дно: потеряно место одно. в испуге считают багаж: диван, чемодан, саквояж, картина, корзина, картонка… — товарищи! где собачонка? вдруг видят: стоит у колес огромный взъерошенный пес. поймали его — и в багаж, туда, где лежал саквояж, картина, корзина, картонка, где прежде была собачонка. приехали в город житомир. носильщик пятнадцатый номер везет на тележке багаж: диван, чемодан, саквояж, картину, корзину, картонку, а сзади ведут собачонку. собака-то как зарычит, а барыня как закричит: — разбойники! воры! уроды! собака — не той породы! швырнула она чемодан, ногой отпихнула диван, картину, корзину, картонку… — отдайте мою собачонку! — позвольте, мамаша! на станции, согласно багажной квитанции, от вас получили багаж: диван, чемодан, саквояж, картину, корзину, картонку и маленькую собачонку. однако за время пути собака могла подрасти!",
  "price": 999,
  "createdAt": "2024-08-12T14:16:55.351Z",
  "views": 20000,
  "likes": 1,
  "imageUrl": "",
},
{
  "id": "8",
  "name": "Новый айфон",
  "price": 100000,
  "createdAt": "2024-08-12T12:16:55.351Z",
  "views": 200000,
  "likes": 302,
  "imageUrl": "",
},
];

export const pagination_test_happy_path = {
  "first": 1,
  "prev": 3,
  "next": 5,
  "last": 41,
  "pages": 41,
  "items": 1012,
  "data": [
    {
      "id": "76",
      "name": "suspendisse potenti in eleifend quam",
      "description": "",
      "price": 2088,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 24,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/105x100.png/ff4444/ffffff",
    },
    {
      "id": "77",
      "name": "nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta",
      "description": "",
      "price": 4045,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/218x100.png/dddddd/000000",
    },
    {
      "id": "78",
      "name": "posuere felis sed lacus morbi sem mauris",
      "description": "sollicitudin mi sit amet lobortis sapien sapien non mi integer ac",
      "price": 4557,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 94,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/245x100.png/cc0000/ffffff",
    },
    {
      "id": "79",
      "name": "felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam",
      "description": "",
      "price": 752,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/207x100.png/dddddd/000000",
    },
    {
      "id": "80",
      "name": "faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus",
      "description": "",
      "price": 3134,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 10,
      "imageUrl": "http://dummyimage.com/206x100.png/cc0000/ffffff",
    },
    {
      "id": "81",
      "name": "quis odio consequat varius integer ac",
      "description": "in ante vestibulum ante ipsum primis in",
      "price": 429,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 5,
      "imageUrl": "http://dummyimage.com/146x100.png/cc0000/ffffff",
    },
    {
      "id": "82",
      "name": "habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat",
      "description": "",
      "price": 1054,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 57,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
    },
    {
      "id": "83",
      "name": "turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc",
      "description": "",
      "price": 1247,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/139x100.png/5fa2dd/ffffff",
    },
    {
      "id": "84",
      "name": "eget orci vehicula",
      "description": "cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum",
      "price": 1051,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 87,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/221x100.png/cc0000/ffffff",
    },
    {
      "id": "85",
      "name": "sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim",
      "description": "",
      "price": 4661,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 57,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/231x100.png/5fa2dd/ffffff",
    },
    {
      "id": "86",
      "name": "maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus",
      "description": "turpis integer",
      "price": 2599,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/231x100.png/ff4444/ffffff",
    },
    {
      "id": "87",
      "name": "et ultrices",
      "description": "",
      "price": 334,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/149x100.png/5fa2dd/ffffff",
    },
    {
      "id": "88",
      "name": "tincidunt ante vel",
      "description": "",
      "price": 2718,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 15,
      "likes": 8,
      "imageUrl": "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
    },
    {
      "id": "89",
      "name": "metus aenean",
      "description": "amet sapien dignissim vestibulum vestibulum ante ipsum",
      "price": 3988,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/117x100.png/cc0000/ffffff",
    },
    {
      "id": "90",
      "name": "gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam",
      "description": "massa donec dapibus duis at velit eu est congue elementum in hac habitasse",
      "price": 1750,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 73,
      "likes": 1,
      "imageUrl": "http://dummyimage.com/145x100.png/cc0000/ffffff",
    },
    {
      "id": "91",
      "name": "dignissim vestibulum vestibulum ante ipsum primis in",
      "description": "felis ut at dolor quis odio consequat",
      "price": 577,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 47,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/230x100.png/ff4444/ffffff",
    },
    {
      "id": "92",
      "name": "penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",
      "description": "",
      "price": 3436,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 49,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
    },
    {
      "id": "93",
      "name": "mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis",
      "description": "hac habitasse platea dictumst etiam",
      "price": 64,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 89,
      "likes": 4,
      "imageUrl": "http://dummyimage.com/209x100.png/ff4444/ffffff",
    },
    {
      "id": "94",
      "name": "et tempus semper est quam pharetra magna ac consequat metus sapien",
      "description": "erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia",
      "price": 1863,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 9,
      "imageUrl": "http://dummyimage.com/100x100.png/ff4444/ffffff",
    },
    {
      "id": "95",
      "name": "elit proin",
      "description": "",
      "price": 1734,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 71,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/144x100.png/ff4444/ffffff",
    },
    {
      "id": "96",
      "name": "est donec odio justo sollicitudin ut suscipit",
      "description": "faucibus cursus urna ut tellus nulla ut erat id",
      "price": 1622,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/206x100.png/dddddd/000000",
    },
    {
      "id": "97",
      "name": "diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
      "description": "",
      "price": 1690,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/118x100.png/ff4444/ffffff",
    },
    {
      "id": "98",
      "name": "in est risus auctor sed",
      "description": "tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa",
      "price": 1318,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 87,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/139x100.png/dddddd/000000",
    },
    {
      "id": "99",
      "name": "eget congue eget semper rutrum nulla nunc purus phasellus in felis",
      "description": "magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien",
      "price": 3988,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 0,
      "likes": 7,
      "imageUrl": "http://dummyimage.com/124x100.png/cc0000/ffffff",
    },
    {
      "id": "100",
      "name": "sem praesent id massa id nisl venenatis lacinia aenean sit amet",
      "description": "",
      "price": 2188,
      "createdAt": "2022-08-12T00:00:00Z",
      "views": 67,
      "likes": 0,
      "imageUrl": "http://dummyimage.com/155x100.png/cc0000/ffffff",
    },
  ],
};
